### ISSUE TITLE
Doesn't work with upload files

### ISSUE THREAD

**Issue by mika31** [pods-framework/pods-gravity-forms#10]
I'm tryiing to use a form with 3 max uploading files in Gravity forms (files are well upload on GF upload folder "wp-content/uploads/gravity_forms/x-xxxxxxxxxxxxxxxxxx/yyyy/mm").

But they are not save in pod record.
Is this functionnality working for someone ?

I've found another plugin with a piece of code that works on the POST['gform_uploaded_files'] var sent by GF  on this page : https://gist.github.com/mmages/2417219

Thank's for your plugin this works well for other fields than uploaded files!

**Comment by ckpicker** [comment]
+1

**Comment by eddallen** [comment]
Hey Scott, Is there any news on this enhancement? I swear i've had it working on a pods build previously..

**Comment by sc0ttkclark** [comment]
No, but I'll take a look at it this weekend.

**Comment by copperleaf** [comment]
I'm working on a project that would greatly benefit from this functionality.  Would a bounty on this particular piece functionality help speed it along?  Thanks!

**Comment by sc0ttkclark** [comment]
I'm currently looking to collaborate here with someone's existing site and configuration if possible. If you have a dev site, then great, but I am looking to do a quick test as I don't have a ton of time this week but I'd really like to finally close this out before New Years :)

Any takers?

**Comment by copperleaf** [comment]
I have a dev site you can use for testing.  Shoot me an email to gordon@copperleafcreative.com and I'll get you credentials.

**Comment by sc0ttkclark** [comment]
Potentially fixed by https://github.com/pods-framework/pods-gravity-forms/commit/e982f82cfacba69ed1bdb5c9b959b07919069cbb -- needs testing to confirm.

**Comment by copperleaf** [comment]
We were just testing this using the form at
http://thewellmont.staging.wpengine.com/?page_id=109 and don't see it
working.  Is there any additional configuration we need to do?

thanks!

Gordon
@CopperGordon


*Copper Leaf Creative*(970) 776-8778
407 N Lincoln, Suite 110
Loveland, CO 80537
www.copperleafcreative.com
*We are in Mountain Time and typically in the office 9-5 PM.*

* <http://www.copperleafcreative.com/>*

**Comment by zanematthew** [comment]
Confirming that this is not fixed, and needs reopening.

**Comment by jimtrue** [comment]
Yep, I can also confirm (from another forum post) that this is not working on multi-upload fields. The fields are being uploaded to the 'entry' but not going into the Media Gallery or the Pods Entry.

**Comment by ZoroG** [comment]
Can confirm also that this is not working for me on either single file or multi-upload fields. I can confirm at least for single file upload that the uploaded image from the file upload filed is uploaded and viewable both on gravity forms entries and the media library.

**Comment by jimtrue** [comment]
For confirmation: 

If you use a 'File Upload' field in your form and _don't_ check Enable Multi-File Upload, this works perfectly for matching uploaded file to image/media/file field in Pods.

Multi-file Upload doesn't work, however. The form performs the upload but it doesn't map to the Pods field.

**Comment by sc0ttkclark** [comment]
Looking at this again, will update once I've got my solution in place.

**Comment by ZoroG** [comment]
Thanks for the update Scott.

**Comment by ZoroG** [comment]
Thanks for the reply Jim

Regards
Michael

**Comment by sc0ttkclark** [comment]
Uploaded files should be working as part of 1.2, is anyone still having issues? Maybe try the latest Pods GF 1.3 work we're doing:
https://github.com/pods-framework/pods-gravity-forms/archive/master.zip

**Comment by ZoroG** [comment]
Fantastic news Scott. Will have a look and test it and report back,

Many thanks
Michael

**Comment by chriswagoner** [comment]
Previous to 1.2 the POD feed would cause the form to hang. This was fixed in 1.2, now it hangs again in 1.3.

**Comment by chriswagoner** [comment]
Reverted back to 1.2 - No image carryover. Perhaps I'm doing something wrong (likely).

**Comment by sc0ttkclark** [comment]
I've pushed some fixes into the master branch (1.3), but I've got a message out to the GF support team to help us refine the upload field value handling for single vs multiple file fields.

**Comment by chriswagoner** [comment]
That fixed the spinner issue. The feed is now processing, even when file upload is enabled, the form submits anyway. Hopefully GF gets back and can resolve the file parse issue.
Thanks.

**Comment by sc0ttkclark** [comment]
I've pushed up some additional fixes/enhancements. Now sub inputs get mapped (mapping a Name [First Name] field to a pod field), but I'm still waiting to hear back from GF support about how to handle the file uploads during the validation stage.

**Comment by sc0ttkclark** [comment]
Phew, finally made it through all of the cases I could think of to cover. Have a go at it! Single or multi both work!

**Comment by chriswagoner** [comment]
Wow, that's great. The uploads *are now working!* They're going into the POD media field **and** to the media library. Sadly, no longer mapping the categories or tags.... so close!

**Comment by jimtrue** [comment]
@chriswagoner Can you please open a separate issue for the categories or tags? (it's really hard to track issues properly when they're combined on one bug report.

**Comment by chriswagoner** [comment]
@jimtrue NP.
