### ISSUE TITLE
Pods Gravity form warning bug

### ISSUE THREAD

**Issue by Michael-Power-135** [pods-framework/pods-gravity-forms#102]
Warning: strlen() expects parameter 1 to be string, array given in /home/djpeteme/public_html/wp-content/plugins/pods/classes/fields/text.php on line 211

Anyone know what might be causing this error appearing after submitting a form from front end despite the form populating all fields correctly after submitting the form. ? A previous post in Git hub recommends trying Pods Gravity Forms Add-On 1.4 (beta) to resolve problem however the error still occurs using 1.4  (beta) as well as 1.3.   https://djpetemello.com/event-submissions/

Gravity Forms 2.2.5.
I have tried both Pods Gravity Forms Add-On 1.3 & Pods Gravity Forms Add-On 1.4 (beta) to no avail. Currently running 1.4 Beta
Pods - Custom Content Types and Fields 2.7.1

**Comment by jimtrue** [comment]
You will need to provide us both a copy of your form (Gravity Forms, Export) and upload the JSON for that form here and also your Pods Structure that you're using the form with, using Pods Admin, Components, Migrate: Packages. Then Export and save the resulting JSON as a text file and upload.

**Comment by jimtrue** [comment]
Also this is a debug "warning" so if you don't want it to be displayed on your front-end, just disable debug warnings in wp-config.php:
https://codex.wordpress.org/Debugging_in_WordPress

**Comment by Michael-Power-135** [comment]
Hi Jim, Thanks for info, I've now disabled the warning on Front end.

**Comment by sc0ttkclark** [comment]
This could be the result of an address field mapped to a single line text field. I'm not sure what the mapping is, perhaps you can screenshot the Pod feed mapping for the form?

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
