### ISSUE TITLE
Cannot create feed

### ISSUE THREAD

**Issue by paddelboot** [pods-framework/pods-gravity-forms#103]
Hi,

When trying to create a new feed in order to map Pods fields to my Gravity Form fields, I just get a blank page “Feed settings”, with nothing to choose from.

Gravity Forms 1.9.18.3
Pods 2.7.1
WordPress 4.9.4
Pods Gravity Forms Add-On 1.3

Thanks for your help.
 (I also posted this issue here: https://wordpress.org/support/topic/cannot-create-new-feed-2/)

**Comment by jimtrue** [comment]
@paddelboot Can you provide us an export of your Pods configuration (ie what Pods you've created) using Pods Admin, Components, Migrate: Packages, Enable? Once you've enabled that component, you can go into Migrate: Packages Export and create a JSON of all your 'pods' and save that to a text file and upload here. Also doing the same with your form would be helpful from Gravity Forms with their Export tool. Thanks!

**Comment by paddelboot** [comment]
Hi Jim,

Thanks for the very quick reply.

Here's the JSON of my "Mitarbeiter (Employee)" Pods:

`{"meta":{"version":"2.7.1","build":1521228307},"pods":{"15":{"id":15,"name":"mitarbeiter","label":"Mitarbeiter","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":16,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_repeatable":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":""},"position":{"id":21,"name":"position","label":"Position","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"abteilung":{"id":22,"name":"abteilung","label":"Abteilung","description":"","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"anrede":{"id":25,"name":"anrede","label":"Anrede","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","pick_custom":"herr|Herr\nfrau|Frau","required":"0","unique":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"kunden-id":{"id":38,"name":"kunden-id","label":"Kunden-ID","description":"","help":"","class":"nodisplay","type":"number","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"default_value":"{@user.ID}","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"1","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""}},"show_in_menu":"1","label_singular":"Mitarbeiter","pod_index":"name","hierarchical":"0","ui_style":"post_type","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":["name"]}}}`

And here's the JSON of the Gravity Form that I'm trying to map:

{"0":{"title":"Mitarbeiter","description":"","labelPlacement":"top_label","descriptionPlacement":"below","button":{"type":"text","text":"Absenden","imageUrl":""},"fields":[{"type":"text","id":1,"label":"Name","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":null,"labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"inputMask":false,"inputMaskValue":"","allowsPrepopulate":false,"formId":1,"description":"","inputType":"","cssClass":"","inputName":"","adminOnly":false,"noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","displayOnly":""},{"type":"text","id":2,"label":"Position","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":null,"labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"inputMask":false,"inputMaskValue":"","allowsPrepopulate":false,"formId":1,"description":"","inputType":"","cssClass":"","inputName":"","adminOnly":false,"noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","displayOnly":""},{"type":"text","id":3,"label":"Abteilung","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":null,"labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"inputMask":false,"inputMaskValue":"","allowsPrepopulate":false,"formId":1,"description":"","inputType":"","cssClass":"","inputName":"","adminOnly":false,"noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","displayOnly":""},{"type":"radio","id":4,"label":"Anrede","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":null,"choices":[{"text":"Herr","value":"Herr","isSelected":false,"price":""},{"text":"Frau","value":"Frau","isSelected":false,"price":""}],"labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"inputMask":false,"inputMaskValue":"","allowsPrepopulate":false,"formId":1,"description":"","inputType":"","cssClass":"","inputName":"","adminOnly":false,"noDuplicates":false,"defaultValue":"","conditionalLogic":"","displayOnly":""},{"type":"number","id":5,"label":"Kunden-ID","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":null,"numberFormat":"decimal_dot","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":false,"disableQuantity":false,"displayAllCategories":false,"inputMask":false,"inputMaskValue":"","allowsPrepopulate":true,"formId":1,"description":"","inputType":"","cssClass":"","inputName":"","adminOnly":false,"noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","rangeMin":"","displayOnly":""}],"version":"1.9.18.3","id":1,"useCurrentUserAsAuthor":true,"postContentTemplateEnabled":false,"postTitleTemplateEnabled":false,"postTitleTemplate":"","postContentTemplate":"","lastPageButton":null,"pagination":null,"firstPageCssClass":null,"confirmations":[{"id":"5aac151303321","name":"Standard Best\u00e4tigung","isDefault":true,"type":"message","message":"Danke, dass Sie uns kontaktiert haben! Wir melden uns zeitnah bei Ihnen.","url":"","pageId":"","queryString":""}],"notifications":[{"id":"5aac15130306d","to":"{admin_email}","name":"Administrator-Benachrichtigung","event":"form_submission","toType":"email","subject":"Neues Anmeldeformular {form_title}","message":"{all_fields}"}]},"version":"1.9.18.3"}

Thanks in advance for looking into it.

**Comment by paddelboot** [comment]
Unfortunately, that didn't help - but I now enabled WP_DEBUG, and it shows this:

`
Fatal error: Uncaught Error: Call to undefined method Pods_GF_Addon::get_slug() in /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/pods-gravity-forms/includes/Pods_GF_Addon.php:372 Stack trace: #0 /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(881): Pods_GF_Addon->feed_settings_fields() #1 /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(713): GFFeedAddOn->get_feed_settings_fields(Array) #2 /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/gravityforms/includes/addon/class-gf-feed-addon.php(658): GFFeedAddOn->feed_edit_page(Array, '0') #3 /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/gravityforms/includes/addon/class-gf-addon.php(3095): GFFeedAddOn->form_settings(Array) #4 /media/Entwicklung/Entwicklung.meilenstein/wp/wp-includes/class-wp-hook.php(286): GFAddOn->form_settings_page('') #5 /media/Entwicklung/Entwicklung.meilenstein/wp/wp- in /media/Entwicklung/Entwicklung.meilenstein/wp/wp-content/plugins/pods-gravity-forms/includes/Pods_GF_Addon.php on line 372`

**Comment by paddelboot** [comment]
I also do have

`define('PODS_SHORTCODE_ALLOW_EVALUATE_TAGS',true);`

in my wp-config.php, if that is of any concern.

**Comment by jimtrue** [comment]
the latter shouldn't make a difference; that's only for allowing magic tags to be evaluated in shortcodes. You might have something else wrong. Also try a Pods Admin, Setting, Clear Cache with all your plugins disabled and see if that clears up your issue.

**Comment by richardW8k** [comment]
@paddelboot the old Gravity Forms version, 1.9.18.3, is the issue. The get_slug method was only added to the add-on framework in Gravity Forms 2.0. The current version of Gravity Forms is 2.2.6.

**Comment by jimtrue** [comment]
^^ there ya go. Didn't even catch that. Thanks @richardW8k !

**Comment by jimtrue** [comment]
@sc0ttkclark Do we need to add a minimum version of Gravity Forms to our Add-on?

**Comment by richardW8k** [comment]
The min version is already defined [here](https://github.com/pods-framework/pods-gravity-forms/blob/master/includes/Pods_GF_Addon.php#L7), but I would recommend bumping it to 2.0 or greater

**Comment by paddelboot** [comment]
Okay, thanks for helping me out. On this page, it also says Gravity Forms 1.9+:

https://de.wordpress.org/plugins/pods-gravity-forms/

Thanks again, will support you with donation.
