### ISSUE TITLE
Multi Select options not being saved within the form when pods field is related to users

### ISSUE THREAD

**Issue by Hornet25** [pods-framework/pods-gravity-forms#107]
## Issue Overview
I have a multi select field in my pods custom post that is set to multi-select format and related to Users. I have a multi-select field in my gravity form that is fed by the pod to display the users. This all works perfectly and I have my form at the foot of the template to edit the custom post through the gravity form. The issue I have is that the gravity form doesn't store the multi-selected options so when additional updates are completed, the multi-select fields go blank. I had this problem before with a yes/no field and changing the values to 1 and 0 solved that. I am guessing this is a values issue but I don't know what values to add as the gravity field is fed by the pod. If the pods field is a custom list then this problem goes away.

## Expected Behavior
I would expect the Gravity Form to highlight the names of the users I had already selected when I came to update the pod, so these records would not be lost.

## Current Behavior
What is happening is the form is not storing the selections I already made so when I save the form for a second time, the names of users I previously selected are being removed from the pod.

## Steps to Reproduce (for bugs)
1. Create a pod with a field related to users
2. Create a feed from a pod to a Gravity Form
3. Add the Gravity Form to the template of the pod and display the template on a website
4. Select multiple users for the specific field and save the Gravity Form so it populates the pod.
5. Once saved, check the Gravity Form and you will see that the names you selected are not highlighted in the form anymore so if you save the form once again the names you previously saved are lost.

## Form Upload

<details>
```
Upload Gravity Form JSON or Copy and Paste it Here.
```
</details>

## Pods Package Export

<details>
```
Copy and Paste the JSON Export from Pods Migrate: Packages, Export and Paste it Here
```
</details>

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by Hornet25** [comment]
Herewith a screen capture video which I hope clarifies the issue I am having.

[Capture 01.zip](https://github.com/pods-framework/pods-gravity-forms/files/1872662/Capture.01.zip)

**Comment by sc0ttkclark** [comment]
Try with the latest Pods GF 1.4 with recent updates: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by sc0ttkclark** [comment]
I believe this is now (further) fixed. Try the latest 1.4 release we're getting ready to put on wordpress.org:

https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip
