### ISSUE TITLE
Gravity Forms 2.3 not compatible

### ISSUE THREAD

**Issue by mgratch** [pods-framework/pods-gravity-forms#108]
## Issue Overview
It appears that this extension directly references tables that are no longer part of GF after version 2.3.  Furthermore from the best that I can tell this is not backwards compatible.

**Comment by sc0ttkclark** [comment]
Yep! Time for an update :|

**Comment by mgratch** [comment]
Doing some testing, update should be coming soon.  I am working off #86 though, so I am not sure other than the merge conflict that I fixed in #100 what else would be keeping this from going live, aside from the need to further test.
