### ISSUE TITLE
Adding a new currency field to an existing template crashes the post

### ISSUE THREAD

**Issue by bennygill** [pods-framework/pods-gravity-forms#111]
## Issue Overview
If a new _currency_ custom field is created and referenced in a template _after_ a post has been published, it will crash the page (the post turns white, header still shows).

**For example this template will crash the page:** [if new_currency_field_added_after_post_creation]Show some stuff[/if]

You have to go and manually "update" each post to fix the crash.

## Expected Behavior
Since the currency is expected to be blank (e.g. no one has gone into the post and added a value and saved the post) the if statement should evaluate to "false" and not return anything.

## Current Behavior
It crashes the post, the entire post turns white (except for the header).

## Steps to Reproduce (for bugs)
1. Create a Pod, a text custom field, and template to display that field.
2. Create a new post to display your template using a shortcode (example: [pods template="My Template"])
3. Edit that pod to include a new currency custom field (example: new_currency)
4. Edit the template from step 1 with an IF statement that references the new field (example: [if new_currency]a[/if])
5. View the post from step 2 _on the front end_. Do not view or "update" the post in admin yet. You will see it has crashed - displays a white screen in place of the content.
6. Now go into that crashed post and click "update". It will come back alive again.

**Comment by jimtrue** [comment]
@bennygill Did you mean to publish this in the Gravity Forms Add-on Bug report area? I think you meant to create this in Pods: https://github.com/pods-framework/pods/issues/new

**Comment by bennygill** [comment]
Whoops! Yes it was supposed to be over there. I'm new to this. Can we move it over somehow?

**Comment by bennygill** [comment]
@jimtrue should I delete this bug report and resubmit to the correct place?

**Comment by jimtrue** [comment]
My apologies, yep. I can close this one if you can resubmit to the correct area. That report actually asks for your debug details so that's a better place to resubmit.
