### ISSUE TITLE
I can't upload photos

### ISSUE THREAD

**Issue by AmiracleDesign** [pods-framework/pods-gravity-forms#112]
Hi
I can not seem to be able to upload photos and set featured image. When I submit a photo in my form it does upload to uploads/gravity_forms/ and I can see it attached to the entry but nothing to the actual page. Can you please let me know what am I doing wrong?

Here you can see my settings:
https://www.screencast.com/t/zAJkEyAV

Thanks
Amir

**Comment by sc0ttkclark** [comment]
Try the latest 1.4 release we're getting ready to put on wordpress.org:

https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
