### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kennym** [pods-framework/pods-gravity-forms#113]
I'd like to help you deploy a new release so Wordpress users who use the plugin from the WP repo can enjoy this plugin with the latest WP version. Could you make a maintainer?

**Comment by spiral-labs** [comment]
Hi Kennym, I hope your release is available soon, is the 1.4 Beta the latest version available?

**Comment by sc0ttkclark** [comment]
I am running the release tonight. Sorry for the delay, I've had a lot of stuff going on, but you are more than welcome to assist in the release process. You can make PRs on this repo and do code reviews (review the changes, test it, confirm it looks good) on the 1.4 release PR https://github.com/pods-framework/pods-gravity-forms/pull/86

I don't normally add contributors immediately to a repo, so you'll want to first contribute through helping out on PRs / testing before we get to that stage. I'm excited to have extra help, thanks for hte offer @kennym!
