### ISSUE TITLE
Bug-Blocker: Select Lists Dynamically Populate but only pass selection from list of option in GF Field

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#115]
## Issue Overview
When using any form of Select/Radio/Checkbox fields in the Gravity Form that are dynamically populated by Pods, the options will be 'overwritten' by the Populated options. All the options load, however, if you leave the field with the default 3 options, those are the only ones passed over in the Feed to Pods. If you increase it to six, six options will pass.

The Add-on needs to ignore 'options' in the form in favor of the ones dynamically populated.

**Comment by jimtrue** [comment]
![](http://sc0tt.me/2Q0s0X2v3C0R/Screen%20Shot%202018-06-27%20at%2012.24.25%20PM.png)

**Comment by jimtrue** [comment]
@sc0ttkclark got a confirmation from someone using the beta that this particular issue still exists.

**Comment by sc0ttkclark** [comment]
Fixed in #86
