### ISSUE TITLE
ERROR: rg_lead_detail table not valid

### ISSUE THREAD

**Issue by tokazama2** [pods-framework/pods-gravity-forms#116]
## Issue Overview
Receiving error: "An outdated add-on or custom code is attempting to access the wp_rg_lead_detail table which is not valid in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data. Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2 in /srv/users/ahacpa/apps/ahacpa/public/wp-content/plugins/gravityforms/gravityforms.php on line 5153"

I am not sure when this started happening.  I have deactivated plugins one by one and determined the conflict to be with the pods-gravity-forms plugin.

## Current Behavior
The form seems to submit the information okay, but the error is displayed for the user after submitting.  This is a form used only for users with certain roles.  I can provide username and password if needed.

## Pods Package Export

<details>
```
{"0":{"title":"Announcement\/News","description":"","labelPlacement":"top_label","descriptionPlacement":"above","button":{"type":"text","text":"Submit","imageUrl":""},"fields":[{"type":"post_title","id":1,"label":"Headline","adminLabel":"","isRequired":false,"size":"large","errorMessage":"","inputs":null,"formId":20,"description":"","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","inputType":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","productField":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":false,"displayOnly":""},{"type":"post_custom_field","id":9,"label":"Keywords","adminLabel":"","isRequired":false,"size":"large","errorMessage":"","inputs":[{"id":"9.1","label":"First Choice","name":""},{"id":"9.2","label":"Second Choice","name":""},{"id":"9.3","label":"Third Choice","name":""}],"inputType":"checkbox","formId":20,"description":"One or two key words. If you were going to do a Google search for this item, what words would you use? If the keyword that you want doesn't show up, <a href=\"\/wp-admin\/edit-tags.php?taxonomy=keyword&post_type=announcements\" target=\"blank\">click here<\/a> to add the keyword.  Then come back to this page and refresh.","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":[{"text":"First Choice","value":"First Choice","isSelected":false,"price":""},{"text":"Second Choice","value":"Second Choice","isSelected":false,"price":""},{"text":"Third Choice","value":"Third Choice","isSelected":false,"price":""}],"conditionalLogic":"","productField":"","enablePasswordInput":"","maxLength":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":false,"postCustomFieldName":"built_in_taxonomies_keyword","displayOnly":"","storageType":"json","pods_populate_related_items":true,"enableEnhancedUI":false,"enableChoiceValue":true},{"type":"post_content","id":4,"label":"Announcement\/News Information","adminLabel":"","isRequired":false,"size":"large","errorMessage":"","inputs":null,"formId":20,"description":"","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","inputType":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","productField":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":true,"displayOnly":""},{"type":"post_custom_field","id":5,"label":"Industry","adminLabel":"","isRequired":false,"size":"medium","errorMessage":"","inputs":[{"id":"5.1","label":"First Choice","name":""},{"id":"5.2","label":"Second Choice","name":""},{"id":"5.3","label":"Third Choice","name":""}],"inputType":"checkbox","formId":20,"description":"Select all that apply","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":[{"text":"First Choice","value":"First Choice","isSelected":false,"price":""},{"text":"Second Choice","value":"Second Choice","isSelected":false,"price":""},{"text":"Third Choice","value":"Third Choice","isSelected":false,"price":""}],"conditionalLogic":"","productField":"","enablePasswordInput":"","maxLength":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":false,"postCustomFieldName":"built_in_taxonomies_industry","enableChoiceValue":true,"pods_populate_related_items":true,"displayOnly":""},{"type":"post_custom_field","id":2,"label":"Support Link (optional)","adminLabel":"","isRequired":false,"size":"large","errorMessage":"","inputs":null,"inputType":"website","formId":20,"description":"This is a link to AHACPA's support page specific to this news item.  This may not always be applicable.  It will guide people to a central location for additional questions.","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"http:\/\/","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","productField":"","enablePasswordInput":"","maxLength":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":false,"postCustomFieldName":"support_page","displayOnly":""},{"type":"post_custom_field","id":3,"label":"Link to News Source (optional)","adminLabel":"","isRequired":false,"size":"large","errorMessage":"","inputs":null,"inputType":"website","formId":20,"description":"If applicable, link to the news source.  i.e. HUD.gov, OIG, etc.","allowsPrepopulate":false,"inputMask":false,"inputMaskValue":"","labelPlacement":"","descriptionPlacement":"","subLabelPlacement":"","placeholder":"http:\/\/","cssClass":"","inputName":"","visibility":"visible","noDuplicates":false,"defaultValue":"","choices":"","conditionalLogic":"","productField":"","enablePasswordInput":"","maxLength":"","multipleFiles":false,"maxFiles":"","calculationFormula":"","calculationRounding":"","enableCalculation":"","disableQuantity":false,"displayAllCategories":false,"useRichTextEditor":false,"postCustomFieldName":"source","displayOnly":""}],"version":"2.2.5","id":20,"useCurrentUserAsAuthor":true,"postContentTemplateEnabled":false,"postTitleTemplateEnabled":false,"postTitleTemplate":"","postContentTemplate":"","lastPageButton":null,"pagination":null,"firstPageCssClass":null,"postAuthor":"1282","postCategory":"1","postFormat":"0","postStatus":"publish","subLabelPlacement":"above","cssClass":"","enableHoneypot":false,"enableAnimation":false,"save":{"enabled":false,"button":{"type":"link","text":"Save and Continue Later"}},"limitEntries":false,"limitEntriesCount":"","limitEntriesPeriod":"","limitEntriesMessage":"","scheduleForm":false,"scheduleStart":"","scheduleStartHour":"","scheduleStartMinute":"","scheduleStartAmpm":"","scheduleEnd":"","scheduleEndHour":"","scheduleEndMinute":"","scheduleEndAmpm":"","schedulePendingMessage":"","scheduleMessage":"","requireLogin":false,"requireLoginMessage":"","confirmations":[{"id":"59b6fa51a7015","name":"Default Confirmation","isDefault":true,"type":"message","message":"Thanks for contacting us! We will get in touch with you shortly.","url":"","pageId":"","queryString":""}],"notifications":[{"id":"59b6fa51a6d48","to":"{admin_email}","name":"Admin Notification","event":"form_submission","toType":"email","subject":"New submission from {form_title}","message":"{all_fields}"}]},"version":"2.3.2"}
```
</details>

## WordPress Environment
<details>
```
WordPress Version: 4.9.5

PHP Version: 7.1.19

MySQL Version: 5.7.22

Server Software: Apache/2.4.33 (Unix) OpenSSL/1.0.2g

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

Session Save Path: /srv/users/ahacpa/tmp/ahacpa

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: aha_

WP Multisite Mode: No

WP Memory Limit: 256M

Pods Network-Wide Activated: No

Pods Install Location: /srv/users/ahacpa/apps/ahacpa/public/wp-content/plugins/pods-release-2.7/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Sunrise Child Theme

Currently Active Plugins:

Admin Columns Pro: 4.3.5
Admin Columns Pro - Pods: 1.2
Admin Menu Editor Pro: 2.6.5
aMember Pro v4 Integration Plugin for Wordpress: 1.1
Awesome Support: 5.1.1
Awesome Support: Auto Close: 1.0.5
Awesome Support: Canned Responses: 2.0.0
Awesome Support: Custom Fields: 2.0.1
Awesome Support: E-Mail Support: 5.1.3
Awesome Support: FAQ: 3.0.2
Awesome Support: Power-Pack (Productivity): 4.3.0
Awesome Support: Public Tickets: 1.1.1
Awesome Support: Smart Agent Assignment: 2.3.0
Beaver Builder Plugin (Standard Version): 2.1.3.5
Beaver Studio: 1.0.0
Beaver Themer: 1.1.2.1
Better Font Awesome: 1.7.1
Broken Link Checker: 1.11.5
Cloudflare: 3.3.2
Control Studio: 0.6.6
Duplicate Post: 3.2.2
EventON: 2.6.11
EventON - Daily View: 1.0.8
EventON - Event Lists: 0.10
EventON - Full cal: 1.1.5
EventON - Speakers & Schedule: 0.12
EventON - Weekly View: 1.0.11
Gravity Forms: 2.3.2
Gravity Forms Polls Add-On: 3.1
Gravity Forms Quiz Add-On: 3.1
Gravity Forms Survey Add-On: 3.2
Members: 2.1.0
Pods - Custom Content Types and Fields: 2.7.6
Pods Beaver Themer Add-On: 1.2.2
Pods Gravity Forms Add-On: 1.4 Beta
Posts Table Pro: 2.0.3
PowerPack for Beaver Builder: 2.6.6
SMTP Studio: 0.9.6
Ultimate Addons for Beaver Builder: 1.8.3
UpdraftPlus - Backup/Restore: 2.14.11.24
Wordfence Security: 7.1.9
```
</details>

**Comment by naomicbush** [comment]
Hi @tokazama2, I'd be interested in seeing the information on the Forms->System Status page

**Comment by tokazama2** [comment]
### Gravity Forms ###

Registration: Not registered ✘ 
Version: 2.3.2 ✔
Upload folder: /srv/users/ahacpa/apps/ahacpa/public/wp-content/uploads/gravity_forms/
Upload folder permissions: Writable  ✔
Output CSS: Yes
Output HTML5: No
No-Conflict Mode: No
Currency: USD
Background updates: Yes
Locale: en_US

### Add-Ons ###

Polls: by Rocketgenius - 3.1  ✔
Quiz: by Rocketgenius - 3.1  ✔
Survey: by Rocketgenius - 3.2  ✔

### Database ###

Database Version: 2.3.2  ✔ Your database is up-to-date.
aha_gf_form_view:   ✔
aha_gf_form_meta:   ✔
aha_gf_form:   ✔
aha_gf_entry:   ✔
aha_gf_entry_meta:   ✔
aha_gf_entry_notes:   ✔
aha_gf_draft_submissions:   ✔

### Log Files ###

Gravity Forms Core: https://ahacpa.org/wp-content/uploads/gravity_forms/logs/gravityforms_a5442fed01392ab83d585f59c15cb13e68f47e4e.txt
Pods Gravity Forms Add-On: https://ahacpa.org/wp-content/uploads/gravity_forms/logs/pods-gravity-forms_3487ce5fe045aa93b31f2fb8c06ead9900c6d7e7.txt

### WordPress ###

Home URL: https://ahacpa.org
Site URL: https://ahacpa.org
WordPress Version: 4.9.5 ✔
WordPress Multisite: No
WordPress Memory Limit: 256M
WordPress Debug Mode: Yes
WordPress Debug Log: Yes
WordPress Script Debug Mode: No
WordPress Cron: Yes
WordPress Alternate Cron: No
Background tasks: Yes  ✔

### Active Theme ###

Sunrise Child Theme: by   - 17.6.29  ✔
Voce Theme (Parent): by Benjamin Bradley (http://b.enjam.in) - 1.9.9.7  ✔

### Active Plugins ###

Admin Columns Pro: by Admin Columns - 4.3.5  ✔
Admin Columns Pro - Pods: by Admin Columns - 1.2  ✔
Admin Menu Editor Pro: by Janis Elsts - 2.6.5  ✔
aMember Pro v4 Integration Plugin for Wordpress: by CGI-Central  - 1.1  ✔
Awesome Support: by Awesome Support Team - 5.1.1  ✔
Awesome Support: Auto Close: by AwesomeSupport - 1.0.5  ✔
Awesome Support: Canned Responses: by The Awesome Support Team - 2.0.0  ✔
Awesome Support: Custom Fields: by The Awesome Support Team - 2.0.1  ✔
Awesome Support: E-Mail Support: by The Awesome Support Team - 5.1.3  ✔
Awesome Support: FAQ: by Awesome Support - 3.0.2  ✔
Awesome Support: Power-Pack (Productivity): by Awesome Support - 4.3.0  ✔
Awesome Support: Public Tickets: by The Awesome Support Team - 1.1.1  ✔
Awesome Support: Smart Agent Assignment: by Awesome Support - 2.3.0  ✔
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team - 2.1.3.5  ✔
Beaver Studio: by Benjamin Bradley - 1.0.0  ✔
Beaver Themer: by The Beaver Builder Team - 1.1.2.1  ✔
Better Font Awesome: by Mickey Kay - 1.7.1  ✔
Broken Link Checker: by Janis Elsts, Vladimir Prelovac - 1.11.5  ✔
Cloudflare: by John Wineman, Furkan Yilmaz, Junade Ali (Cloudflare Team) - 3.3.2  ✔
Control Studio: by Benjamin Bradley - 0.6.6  ✔
Duplicate Post: by Enrico Battocchi - 3.2.2  ✔
EventON: by AshanJay - 2.6.11  ✔
EventON - Daily View: by Ashan Jay - 1.0.8  ✔
EventON - Event Lists: by Ashan Jay - 0.10  ✔
EventON - Full cal: by Ashan Jay - 1.1.5  ✔
EventON - Speakers & Schedule: by Ashan Jay - 0.12  ✔
EventON - Weekly View: by Ashan Jay - 1.0.11  ✔
Members: by Justin Tadlock - 2.1.0  ✔
Pods - Custom Content Types and Fields: by Pods Framework Team - 2.7.6  ✔
Pods Beaver Themer Add-On: by Quasel, Pods Framework Team - 1.2.2  ✔
Pods Gravity Forms Add-On: by Pods Framework Team - 1.4 Beta  ✔
Posts Table Pro: by Barn2 Media - 2.0.3  ✔
PowerPack for Beaver Builder: by Team IdeaBox - Beaver Addons - 2.6.6  ✔
SMTP Studio: by Benjamin Bradley - 0.9.6  ✔
Ultimate Addons for Beaver Builder: by Brainstorm Force - 1.8.3  ✔
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com, DavidAnderson - 2.14.11.24  ✔
Wordfence Security: by Wordfence - 7.1.9  ✔

### Web Server ###

Software: Apache/2.4.33 (Unix) OpenSSL/1.0.2g
Port: 443
Document Root: /srv/users/ahacpa/apps/ahacpa/public

### PHP ###

Version: 7.1.19 ✔
Memory Limit: 256M
Maximum Execution Time: 30
Maximum File Upload Size: 512M
Maximum File Uploads: 20
Maximum Post Size: 1024M
Maximum Input Variables: 5000
cURL Enabled: Yes (version 7.47.0)
OpenSSL: OpenSSL 1.0.2g  1 Mar 2016 (268443775)
Mcrypt Enabled: Yes
Mbstring Enabled: Yes
Loaded Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, calendar, ctype, dom, fileinfo, filter, ftp, hash, iconv, json, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, snmp, soap, sockets, standard, tokenizer, xml, xmlreader, xmlwriter, zip, mysqlnd, cgi-fcgi, bcmath, Phar, curl, mbstring, gd, gettext, gmp, imap, intl, ldap, exif, mcrypt, mysqli, odbc, pcntl, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, shmop, tidy, xmlrpc, xsl, Zend OPcache

### MySQL ###

Version: 5.7.22 ✔
Database Character Set: utf8mb4
Database Collation: utf8mb4_unicode_ci

**Comment by richardW8k** [comment]
Are sure Pods is causing this? To date the most common cause has been the UpdraftPlus plugin which is also included in your system report. You can either exclude the old tables from backups or remove the old tables if you are sure they are no longer required: https://docs.gravityforms.com/upgrading-to-gravity-forms-2-3/#can-i-delete-the-deprecated-tables-once-the-upgrade-is-complete-

**Comment by tokazama2** [comment]
@richardW8k: I deactivated UpdraftPlus, I removed the deprecated tables.  That didn't fix my problem.  Then I re-installed the pods-gravity-forms plugin and the problem seems to be solved.  I'll continue with some testing.

**Comment by MGParisi** [comment]
Im also getting this error.  I do not have that either.

Here is the call stack for me...


1 | 0.4055 | 375520 | {main}( ) | ...\index.php:0
-- | -- | -- | -- | --
2 | 0.4057 | 377552 | require( 'C:\wamp64\www\eponies-wp\wp-blog-header.php' ) | ...\index.php:17
3 | 0.7480 | 46158880 | wp( ) | ...\wp-blog-header.php:16
4 | 0.7480 | 46158928 | WP->main( ) | ...\functions.php:960
5 | 0.7540 | 46244176 | do_action_ref_array( ) | ...\class-wp.php:726
6 | 0.7540 | 46244176 | WP_Hook->do_action( ) | ...\plugin.php:515
7 | 0.7540 | 46244176 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:310
8 | 0.7541 | 46246552 | GFForms::maybe_process_form( ) | ...\class-wp-hook.php:286
9 | 0.7604 | 46972352 | GFFormDisplay::process_form( ) | ...\gravityforms.php:593
10 | 0.7892 | 48600376 | GFFormDisplay::handle_submission( ) | ...\form_display.php:137
11 | 1.1411 | 49034368 | gf_apply_filters( ) | ...\form_display.php:1417
12 | 1.1411 | 49035160 | apply_filters( ) | ...\gravityforms.php:5458
13 | 1.1412 | 49035880 | WP_Hook->apply_filters( ) | ...\plugin.php:203
14 | 1.1454 | 49022008 | Pods_GF->_gf_entry_post_save( ) | ...\class-wp-hook.php:288
15 | 1.1455 | 49022384 | wpdb->get_results( ) | ...\Pods_GF.php:3553
16 | 1.1455 | 49022320 | wpdb->query( ) | ...\wp-db.php:2488
17 | 1.1455 | 49022320 | apply_filters( ) | ...\wp-db.php:1789
18 | 1.1455 | 49022720 | WP_Hook->apply_filters( ) | ...\plugin.php:203
19 | 1.1455 | 49023472 | GFForms::filter_query( ) | ...\class-wp-hook.php:286
20 | 1.1456 | 49024480 | trigger_error ( ) | ...\gravityforms.php:5153

**Comment by MGParisi** [comment]
The full error... Notice: An outdated add-on or custom code is attempting to access the wp_eponies_rg_lead_detail table which is not valid in this version of Gravity Forms. Update your add-ons and custom code to prevent loss of form data. Further details: https://docs.gravityforms.com/database-storage-structure-reference/#changes-from-gravity-forms-2-2 in C:\wamp64\www\eponies-wp\wp-content\plugins\gravityforms\gravityforms.php on line 5153

**Comment by MGParisi** [comment]
### Gravity Forms ###

Registration: Site registered ( f77b7977-9661-4dcc-bfd6-3343b8e3d745 )  ✔
Version: 2.3.3.4 ✔
Upload folder: C:\wamp64\www\eponies-wp/wp-content/uploads/gravity_forms/
Upload folder permissions: Writable  ✔
Output CSS: Yes
Output HTML5: Yes
No-Conflict Mode: No
Currency: USD
Background updates: Yes
Locale: en_US

### Database ###

Database Version: 2.3.3.4  ✔ Your database is up-to-date.
wp_eponies_gf_form_view:   ✔
wp_eponies_gf_form_meta:   ✔
wp_eponies_gf_form:   ✔
wp_eponies_gf_entry:   ✔
wp_eponies_gf_entry_meta:   ✔
wp_eponies_gf_entry_notes:   ✔
wp_eponies_gf_draft_submissions:   ✔

### WordPress ###

Home URL: http://localhost/eponies-wp
Site URL: http://localhost/eponies-wp
WordPress Version: 4.9.8 ✔
WordPress Multisite: No
WordPress Memory Limit: 40M
WordPress Debug Mode: Yes
WordPress Debug Log: Yes
WordPress Script Debug Mode: No
WordPress Cron: Yes
WordPress Alternate Cron: No
Background tasks: Yes  ✔

### Active Theme ###

Twenty Seventeen: by the WordPress team (https://wordpress.org/) - 1.7  ✔

### Active Plugins ###

Advanced Custom Fields: by Elliot Condon - 4.4.12  ✔
Akismet Anti-Spam: by Automattic - 4.0.8  ✔
DK PDF: by Emili Castells - 1.9.6  ✔
Nav Menu Roles: by Kathy Darling - 1.9.2  ✔
Panda Pods Repeater Field: by Dongjie Xu - 1.2.1  ✔
Picks: by Michael Parisi - 2.0.0  ✔
Pods - Custom Content Types and Fields: by Pods Framework Team - 2.7.8  ✔
Pods Gravity Forms Add-On: by Pods Framework Team - 1.3  ✔
Restrict Content Pro: by Restrict Content Pro Team - 2.9.13  ✔
Restrict Content Pro - MailChimp Pro: by Restrict Content Pro Team - 1.4.2  ✔
URL Params: by Jeremy B. Shapiro - 2.1  ✔
WP Crontrol: by John Blackbourn & contributors - 1.6.2  ✔

### Web Server ###

Software: Apache/2.4.33 (Win64) PHP/7.1.16
Port: 80
Document Root: C:/wamp64/www

### PHP ###

Version: 7.1.16 ✔
Memory Limit: 1G
Maximum Execution Time: 960
Maximum File Upload Size: 4096M
Maximum File Uploads: 20
Maximum Post Size: 9012M
Maximum Input Variables: 5000
cURL Enabled: Yes (version 7.59.0)
OpenSSL: OpenSSL 1.0.2o  27 Mar 2018 (268443903)
Mcrypt Enabled: Yes
Mbstring Enabled: Yes
Loaded Extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, apache2handler, openssl, curl, com_dotnet, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xmlrpc, xsl, Zend OPcache, xdebug

### MySQL ###

Version: 5.7.21 ✔
Database Character Set: latin1
Database Collation: latin1_swedish_ci

**Comment by nicdford** [comment]
I am seeing this same notice using pods + pods gravity add on

**Comment by nicdford** [comment]
I've tested this against version 1.4 and it looks to resolve this issue. @sc0ttkclark

**Comment by sc0ttkclark** [comment]
FYI -- This issue still happens when you go to edit a pod, because Pods stores a transient with a list of all available tables in the database. Because this list of tables includes old GF tables, it triggers the warning in those cases. Just something to be aware of, removing the old tables will resolve the issue.
