### ISSUE TITLE
post_id in $entry array is null in gf hooks

### ISSUE THREAD

**Issue by svaults** [pods-framework/pods-gravity-forms#119]
## Issue Overview
The post_id in $entry array is null in gf hooks

## Expected Behavior
The post id for the newly created custom post should be available - I'm trying to redirect to this new post using the "gform_entry_post_save" filter

## Current Behavior
The post_id is null in this array

## Possible Solution
Populate the post_id through an earlier filter

## Steps to Reproduce (for bugs)

1. Create a custom post type pod
2. Create a gravity form to create new cpt
3. Create pod and try to access newly created id in a filter e.g. 'gform_entry_post_save'

## Form Upload

<details>
```
Upload Gravity Form JSON or Copy and Paste it Here.
```
</details>

## Pods Package Export

<details>
```
Copy and Paste the JSON Export from Pods Migrate: Packages, Export and Paste it Here
```
</details>

## Todos
- [x] Tests
- [x] Documentation

## WordPress Environment
<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
