### ISSUE TITLE
Published post modified by gravity form w/ pods feed reverts to draft on form submission

### ISSUE THREAD

**Issue by RKain** [pods-framework/pods-gravity-forms#120]
## Issue Overview

I have a pod called "car"; The single page of this pod contains, among other things, a gravity form to edit its contents. Submitting this form changes the pod from "published" to "draft". The default status of the pod is set to "publish" in Pods > Edits Pods > Car > Advanced Options, so whatever the issue is, it's not that.

## Expected Behavior

When I submit a form that edits an existing pod (by virtue of being embedded in the single page), it should retain its current post status ("publish" if published, "draft" if draft)

## Current Behavior

No matter what the previous status of the post, submitting the form forces the post to be set to "draft" status.

## Steps to Reproduce (for bugs)

1. Embed a gravity form with a properly configured pods feed in the template of a single page of a pod.
2. In the pods feed, Check "Enable editing with this form for current post" and "Enable populating field values for this form using current post"
3. Navigate to the single page of a published post of the pod in question.
4. Submit the form, with or without changes
5. The post is now a draft

## Form Upload

<details>
```
Upload Gravity Form JSON or Copy and Paste it Here.
```
</details>

## Pods Package Export

<details>
```
Copy and Paste the JSON Export from Pods Migrate: Packages, Export and Paste it Here
```
</details>

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
Debug Information
WordPress Version: 4.9.8

PHP Version: 7.2.8

MySQL Version: 5.7.23

Server Software: Apache/2.4.34 (Unix) OpenSSL/1.0.2g

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

Session Save Path: /srv/users/cityautobahn/tmp/cityautobahn

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_18f369f988_

WP Multisite Mode: Yes

WP Memory Limit: 256M

Pods Network-Wide Activated: Yes

Pods Install Location: /srv/users/cityautobahn/apps/cityautobahn/public/site-files/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Summit - Autobahn

Currently Active Plugins:

Anti-Splog: 2.2.1
Appointments+: 2.4.0
Autobahn Market Pro: 1.3.1
BackupBuddy: 8.2.8.0
Bookly: 15.1
Bookly Chain Appointments (Add-on): 1.5
Bookly Google Maps Address (Add-on): 1.1
Bookly Invoices (Add-on): 1.1
Bookly Locations (Add-on): 2.0
Cloner: 1.7.7
Cloudflare: 3.3.2
Defender Pro: 1.9.1
Google Analytics +: 3.1.7.1
Google Maps Pro: 2.9.4
Gravity Forms: 2.3.3
Gravity Forms Business Hours by GravityView: 2.1
Gravity Forms Chained Selects Add-On: 1.1
Gravity Forms User Registration Add-On: 3.9
GravityView - Gravity Forms Import Entries: 1.3.3
Gutenberg: 3.6.2
LoopBuddy: 1.4.35
MarketPress: 3.2.8
Membership 2 Pro: 1.1.5
Pods - Custom Content Types and Fields: 2.7.9
Pods Gravity Forms Add-On: 1.3
Pro Sites: 3.5.9.3
SmartCrawl: 2.2.2
Smush Pro: 2.8.0
Snapshot Pro: 3.1.9.1
Ultimate Branding: 2.1.0
WPMU DEV Dashboard: 4.5.2
</details>

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
