### ISSUE TITLE
Problem with mapping relation field

### ISSUE THREAD

**Issue by zarianka** [pods-framework/pods-gravity-forms#126]
Below is not an actual example but just an attempt of a simple illustration of my problem.

I have two **ACT** pods, let say ‘films’ and ‘actors’. I plan to store variable qty of actors in ‘films’->’stars’ relation field. I mapped ‘films’->’stars’  to GF field called 'Star team' ('Advanced Fields' ->'List Field'). Because of very-very long list of 'actors' I prefer add actors to the 'Star team' field by actors->slug (name). 

I added two 'Star team' rows and filled them with actors->slug. I expected new films item will be saved with these items stored in ‘films’->’stars’.

If 'Star team' option 'Enable multiple columns' is not selected on submitting process is stoped with the error: array_keys() expects parameter 1 to be array, string given in …\Pods_GF.php on line 3521.

If option is selected and ‘films’->’stars’ is re-mapped to whole 'Star team' after submitting 4 new pods 'actors' are created with empty field 'name' (slug).
  
If option is selected and ‘films’->’stars’ is re-mapped to 'Star team' (Column1) after submitting 2 new pods 'actors' are created and again with empty field 'name' (slug).

**Comment by jimtrue** [comment]
Looks like you answered your question in this support forum message https://wordpress.org/support/topic/what-gf-field-is-correct-for-use-with-a-pods-relation-field-multy/
We are closing this issue as it seems this was a support issue 


If you're still having issues or feel there is a bug in the list field handling or an opportunity for an enhancement, please let us know in this ticket.
