### ISSUE TITLE
pods addon form settings UI is messed up in GF 2.5

### ISSUE THREAD

**Issue by devlamconstructie** [pods-framework/pods-gravity-forms#152]
the form settings UI is showing html code for field names and descriptions when combined with gf 2.5

![image](https://user-images.githubusercontent.com/66801041/116575619-19f4a880-a90f-11eb-80f4-2f280997bf4f.png)

**Comment by sc0ttkclark** [comment]
Fixed in 2.0, cleaned up interface a bit too
