### ISSUE TITLE
Pods feed mapping UI is not rendering correctly

### ISSUE THREAD

**Issue by nicdford** [pods-framework/pods-gravity-forms#156]
## Issue Overview
It looks like they've changed how they render HTML, so now it's returning tags instead of rendered HTML.
![image](https://user-images.githubusercontent.com/7292444/150883284-ab648ab6-5da2-48c4-b88e-c438d71fed26.png)

## Expected Behavior
For the code to be rendered as HTML and not a string.

## Current Behavior
HTML code is being rendered as a string.

**Comment by TooTallTye** [comment]
Same here cannot select a field to link pod to

**Comment by sc0ttkclark** [comment]
Fixed the HTML code in Pods GF 1.5 and there's a better fix in Pods GF 2.0 that improves that screen.
