### ISSUE TITLE
Can't process form

### ISSUE THREAD

**Issue by schutzsmith** [pods-framework/pods-gravity-forms#22]
Haven't been able to get this to work yet on two different sites. 

I submit the form and then it says: "Either Pod ID or Name are required"

Not sure what we need to do on our end to make this actually work.

We are trying to just set the title and body of a Post and a Page. Trying to run two of these at the same time but even when we try one we get the same error. We have the most recent versions of Pods, Gravity Forms, and the Pods Gravity Forms plugins.

It did process the entries into Gravity Forms, but nothing happened for the Pods.

**Comment by sc0ttkclark** [comment]
Closing this as fixed by recent commits.
