### ISSUE TITLE
dublicate posts if form has more than one step

### ISSUE THREAD

**Issue by maher-samir** [pods-framework/pods-gravity-forms#23]
hello there,

on 
wp 4.0
gf 1.8.18
pods 2.4.3
Pods Gravity Forms Add-On 1.0 Alpha 8

if we create form with two steps for example (make steps with page break) and map this form with our pods. 
on the 1st step of our form a new post has been inserted in our pods - no problem
on the 2nd step also the same data has been inserted in our pods

thanks.

**Comment by sc0ttkclark** [comment]
Currently we process on validation, but validation runs on every page (except when going back to a previous page). We'll have to update Pods_GF to accept an alternative to validation hooks when in use by a GF pod feed, to use the submission hook instead.

**Comment by sc0ttkclark** [comment]
Potential fix for this in https://github.com/pods-framework/pods-gravity-forms/commit/1480e522aacba90921ec23ceb1dc95d514a711e8 -- Needs testing to confirm
