### ISSUE TITLE
Migrate existing GF Entries into Pod feed

### ISSUE THREAD

**Issue by 3dp** [pods-framework/pods-gravity-forms#26]
If I have forms with data that has already been entered is it possible to have it loaded into the Pod?

**Comment by Shelob9** [comment]
Right now there is no way to do that. It would be a cool feature. @naomicbush (https://gravityplus.pro/) might be able to help you find a way to do this.

**Comment by sc0ttkclark** [comment]
Not available currently, but I've been building CLI commands for my purposes here, I could try and generalize it and post something to help you out, maybe in the next week or two.

**Comment by ricemann** [comment]
Hi guys - any news on this ?

I know you are busy like the rest of us ; )
But could be nice to combine my two fav plugins.  Or a plain old crud tutorial would be a treat.

Cheers : )

**Comment by sc0ttkclark** [comment]
No news on this, it's not a current priority as we're focusing on Pods 3.0 development

**Comment by lkraav** [comment]
The announcement e-mail doesn't cover much about the "why and when would you use this" part. But thinking about it and then seeing this issue posted, it's starting to look like having a post-type based data storage model instead of entries, for whatever reason, is the primary purpose of the whole addon, huh?

**Comment by sc0ttkclark** [comment]
Actually, because Pods does any content type, the primary purpose is to map your Gravity Form submissions to any pod type and it's fields. That means it can be a Post Type, Taxonomy, User, Comment, or an Advanced Content Type (custom table).

**Comment by Pietroibba** [comment]
Hi, I know that are a very old topic, but maybe in this two years something changes:

I need, in a gravity form (using Pods + GF + pods plugin for GF), to load an existent pod row data (create using separated table, not in posts table) to update it.

Do you know if is actually possible to do?

**Comment by Brian-Milnes** [comment]
Uh, oh.
This limitation just tripped me up.
I am busy building based on Pods and GF, then find we can only Create, rather than Edit.
So my Plan to use Gravity Flow, to pass Gravity Forms between different Users, for them to amend and append, is up in smoke?

**Comment by Pietroibba** [comment]
So do you think it's not possible to load fields into GF fields?

**Comment by Brian-Milnes** [comment]
No, you can Create Pods fields data with GF, but afterwards it isn't possible to edit that field with GF (only 'C'reate, from CRUD model)
The GF fields (entries) have no relationship with Pods fields once created.

**Comment by jimtrue** [comment]
@Brian-Milnes That's actually not accurate. We maintain a filter `pods_gf_addon_edit_id` that is designed to populate an existing record to edit.
`add_filter( 'pods_gf_addon_edit_id', 'my_set_the_id' );` where `my_set_the_id` is the function you use to return the correct ID.

https://github.com/pods-framework/pods-gravity-forms/blob/master/includes/Pods_GF_Addon.php#L618

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)

There will be documentation on how to run the WP-CLI command to sync entries from GF to Pods (based on the Pods feed) in the release post.
