### ISSUE TITLE
post_title remains empty

### ISSUE THREAD

**Issue by elifafd** [pods-framework/pods-gravity-forms#30]
I have a pod with a few fields.
I have Grafivity Forms (with the pods addition) where i store and map the filled form to the pod.

All fields work except the Title (post_title) name?

Any suggestions?

**Comment by jimtrue** [comment]
This appears to be a cross-post from our Forums:
http://pods.io/forums/topic/set-title-from-gravity-form/

@naomicbush I've done as much troubleshooting as I can with the person on the forum post. Is this one you have time to help investigate?

**Comment by maxidigi** [comment]
Good day...Curious to learn if there had been any additional investigation on this?  I am running into the identical issue?  Trying to have the Pods title populated via a GF field and the Pods field remains blank while the other GF fields populate the Pods fields as expected.

thanks.

**Comment by jimtrue** [comment]
The actual issue you might be having is that you have to use one of the WP Object Fields for 'Post Title'. When you're inserting the fields, you want to use the block called 'Post Fields'. If you select 'Post Fields' from the right field selection and 'Title' for your post_title and map it in the Pods Mapping within WP Object Fields, this works perfectly.

Is that what you're doing @maxidigi or @elifafd ?

**Comment by jimtrue** [comment]
Unfortunately, the wp object fields once mapped are also writing to wp_posts as 'post' in addition to the custom post type. If the mapping occurs for WP Object fields, they should only map to the Custom Post Type.

**Comment by sc0ttkclark** [comment]
Potentially fixed by https://github.com/pods-framework/pods-gravity-forms/commit/e982f82cfacba69ed1bdb5c9b959b07919069cbb -- needs testing to confirm.
