### ISSUE TITLE
Does not work with List field

### ISSUE THREAD

**Issue by WebEndev** [pods-framework/pods-gravity-forms#31]
Hello,

When using a list field, no values are passed over. In addition, it creates multiple posts, one for each list line item submitted.

Very helpful plugin though. Thanks for the work on it.

P.S. - 
WP version 4.3.1
Gravity Forms 1.9.14
Pods 2.5.5

**Comment by sc0ttkclark** [comment]
Interesting issue! I don't think we have thoroughly tested list item or file upload field support. We'll circle back around on this one.

What type of field are you mapping the GF list field to in Pods?

**Comment by WebEndev** [comment]
Hi Scott,

Mapping it to a plain text. Wish I had not removed the entire setup (I decided to go another route), or I could give you more details.

Thanks for the quick response!

**Comment by thecxguy** [comment]
I'm experiencing the same issue.
My pods field type is Relationship>Simple>custom defined list>Multiple Select/Checkboxes
My gform field is a checkbox. 

mapping the pod field to  "FormFieldname (Selected)"

They match exactly
fwiw I have 8 options. 

If the first option is selected, that value is passed through.

**Comment by sc0ttkclark** [comment]
Potentially fixed by https://github.com/pods-framework/pods-gravity-forms/commit/e982f82cfacba69ed1bdb5c9b959b07919069cbb -- needs testing to confirm.
