### ISSUE TITLE
Doesn't work with "name (full)" advanced field

### ISSUE THREAD

**Issue by thecxguy** [pods-framework/pods-gravity-forms#32]
name (first), name (last), can be mapped properly, however name (full) throws an error. I believe it's caused by the fact that gf is passing it as an array rather than a concatenated string.

**Comment by sc0ttkclark** [comment]
Potentially fixed by https://github.com/pods-framework/pods-gravity-forms/commit/e982f82cfacba69ed1bdb5c9b959b07919069cbb -- needs testing to confirm.

**Comment by leeburstroghm** [comment]
Verified, full name fields to not map to gravity forms.. 
GF pods feed displays all GF(Full Name Fields) and I am able to map them accordingly.. to each pod field, lik Prefix -> xx or Middle-> xx
GF entry looks like it saves the Full name fields into one field. . So perhaps the values are not actually separate by the time its available to the pods feed?? 
I was able to verify that if I map GF Full Name(full) to the pods->txt_field and the values populated.

So I am thinking the GF Full Name Advanced field, actually concatenates all the txt fields into a single string to a single db column called full name... I have not checked the DB, I dont feel like searching the GF schema .. I just wont use the full name field as it currently works!

**Comment by leeburstroghm** [comment]
Sorry scott, I see you did a commit .. I am not sure if that is the ver I am running, so I cant verify if its working with that commit!

**Comment by nicdford** [comment]
@sc0ttkclark inadvertently tested this issue. Does seem to work now, but does pop a warning message: `Warning: strlen() expects parameter 1 to be string, array given in /home/********/public_html/wp-content/plugins/pods/classes/fields/text.php on line 202`

**Comment by sc0ttkclark** [comment]
Will revisit this week

**Comment by sc0ttkclark** [comment]
Fixed in latest changes from tonight
