### ISSUE TITLE
Featured Image is Mapping and Saving to Pod post but not Uploading to Media Library

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#35]
Related to this forum post:
http://pods.io/forums/topic/problem-to-feed-featured-image-object-with-pods-gravity-form-plugin/

Featured Image is mapped to Featured Image in WP Object Block on Pods Processor. Entry is written like it's been uploaded to Media Library, but all I see there is a "broken image", like the upload didn't take place.

**Comment by edse83** [comment]
Any updates on this?

**Comment by sc0ttkclark** [comment]
I should have some more time to test this out this week, if you want to confirm, just keep an eye here for an update and I'll let you know when the fix is up on GitHub :)

**Comment by copperleaf** [comment]
Great!  We're anxious to have this working too.  We'll keep an eye here.  Thank you!

**Comment by jimtrue** [comment]
This works if you just use a regular 'image' upload field, but Post Image doesn't map. See #39 for updates.

**Comment by sc0ttkclark** [comment]
Working as of the latest changes from tonight

**Comment by HBMBR** [comment]
Hi i seem to be facing this problem, the issue is also extending to Multi-select as well.
