### ISSUE TITLE
Unable To "Fetch" Custom Taxonomy's Term List Using PODS Feeds

### ISSUE THREAD

**Issue by korgonthurus** [pods-framework/pods-gravity-forms#37]
I'm unable to get the custom taxonomy's values by using the pods feed.

It does work with simple relationship and advanced relationship fields, correctly getting all the values, but not for taxonomies. This happens in the dropdown field, where we can either add our own options to the selections, or fetch them through the associated pod feed.

The taxonomy is correctly mapped in the feed, but I get the default choices of gravity forms, instead of the available terms of the custom taxonomy (whereas when using relationship fields I'm able to get all the correct values).

In more detail: 

That means that e.g. I'm able to pass the right term in my form, it will map correctly. But this means that either a) I have manually listed all my options from within GF's dropdown (which is unusable, many taxonomies might have hundred of terms, as well as get bigger / change frequently), or b) "guess" the term, and type it. It will map correctly. (of course unusable for UGC as well) 

**Sub-Issue**

I guess this should be in here as well, I can't get default dynamic values in the fields. (for example auto complete certain taxonomies, based on the current post's terms.) I'm guessing these issues are interrelated, so I'm dropping this one here as well. (default values will work, for example hardcoding with text a term. when trying to use either GF's dynamic filters or even custom php functions, it won't get the expected result)

**Comment by sc0ttkclark** [comment]
Fixed as of the changes tonight in Pods GF, but requires the fix for Pods 2.x here to work: https://github.com/pods-framework/pods/pull/3437
