### ISSUE TITLE
drop down or selection fields

### ISSUE THREAD

**Issue by bluedition** [pods-framework/pods-gravity-forms#38]
I have been searching throughout for a “drop down” or selection field type. Am I just overlooking this or is there a special way to implement this. I would assume that a selection field would be standard; am I barking up the wrong tree?

**Comment by jimtrue** [comment]
Do you mean a drop down field populated by an existing relationship field or a custom taxonomy or something else?

**Comment by jimtrue** [comment]
@bluedition Did you have any further feedback on what you were looking for? If you don't respond, I'll have to close this issue.

**Comment by VR-Architect** [comment]
I was looking for the instructions on how to get the dropdown to show the values of an advanced content type. The control is mapped to Pods, just doesn't show the Pods value in the dropdown.
