### ISSUE TITLE
Pods Gravity Forms 1.0 release

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods-gravity-forms#39]
Making a list of things that aren't working that we want to work for 1.0 release.

- [x] Delete entry after submission
- [x] Post Image doesn't map to Featured Image for Post
- [x] Custom Taxonomy doesn't map like Relationship Fields (see #37 )
- [x] GF Euro Currency (at GF level) doesn't map to Pods Currency EU Field (comes over as 0,00) (see #34)
- [x] Add FAQ (where folks go for Support, etc.)

**Comment by sc0ttkclark** [comment]
Ready to go up on wordpress.org later today :)

**Comment by devloprs** [comment]
I am still having this issue. I can see it in the media gallery but it is not mapping to the featured image in my post cpt. Am I missing the solution to that issue somewhere?

Thanks Kindly,
Brad

**Comment by jimtrue** [comment]
How are you defining the field map in the Pods Processor and what type of field are you using in your form? Screenshots of the two areas are okay to submit here.

**Comment by jimtrue** [comment]
@devloprs please open that as a new issue or add onto #35
