### ISSUE TITLE
how to get id of pod created in form

### ISSUE THREAD

**Issue by saltnpixels** [pods-framework/pods-gravity-forms#46]
im guessing POD ID is the new id of the created pod from the form.
except it always returns 0.
I am trying to get the pod id that gets created so i can do more stuff with it after the form is submitted...

**Comment by saltnpixels** [comment]
So i have realized that the pod is not created first. It is created after all hooks from gravity form have run and so there is no way to access the pod id because it doesnt exist yet.

**Comment by sc0ttkclark** [comment]
If you want to customize the edit ID you can try something like the code in #55 

If you want to access the new pod item ID, you can try hooking into the `pods_gf_to_pods` action:

```php
add_action( 'pods_gf_to_pods', 'my_hook', 10, 5 );

/**
 * @param Pods $pod
 * @param string $save_action
 * @param array $data
 * @param int $id
 * @param Pods_GF $pods_gf
 */
function my_hook( $pod, $save_action, $data, $id, $pods_gf ) {

    // Do what you want to do here

    // You can access the form ID in $pods_gf->form_id

}

```

**Comment by saltnpixels** [comment]
If I customize the edit ID, will it populate any custom fields in the form?

thanks

--
Eric (Shamai) Greenfield
SaltnPixels.com | shamai@saltnpixels.com

**Comment by sc0ttkclark** [comment]
No, this is after the data has already been saved.

You can customize the field values before Pods save them with another hook:

```php
// 123 is the form ID
add_filter( 'pods_gf_to_pods_data_123', 'my_hook', 10, 3 );

/**
 * @param array $data
 * @param array $form
 * @param array $options
 */
function my_hook( $data, $form, $options ) {

    // Modify some fields
    $data['my_pod_field'] = 'Some other value';

    return $data;

}
```
