### ISSUE TITLE
Cannot save Address

### ISSUE THREAD

**Issue by saltnpixels** [pods-framework/pods-gravity-forms#47]
I cannot seem to save or get an Address field into pods in any way. Either throws an error or just doesnt save.

**Comment by sc0ttkclark** [comment]
Open to ideas on how best to map the address field to a field value.

It would go somewhere around here:
https://github.com/pods-framework/pods-gravity-forms/blob/master/includes/Pods_GF.php#L2967

```
		if ( in_array( $gf_field->type, array( 'name' ) ) ) {
			$value = implode( ' ', $value );
		}
```

Maybe we should just add an address field conditional which implodes separated by comma?

**Comment by JoryHogeveen** [comment]
When it's done, let's integrate it with the Address field.
https://github.com/pods-framework/pods/pull/3634

**Comment by saltnpixels** [comment]
Gravity forms allows you to output whole or parts of the address in an email. So I think similarly we should be able to save either the whole thing as a string or parts in separate custom fields I guess.

thanks

--
Eric (Shamai) Greenfield
SaltnPixels.com | shamai@saltnpixels.com

**Comment by sc0ttkclark** [comment]
Related: https://github.com/pods-framework/pods-gravity-forms/issues/42

**Comment by sc0ttkclark** [comment]
Please try the latest 1.4 release: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip
