### ISSUE TITLE
Author not being stored for custom post type

### ISSUE THREAD

**Issue by javaandy1** [pods-framework/pods-gravity-forms#48]
Hi, 

Jim had asked me to leave a bug report here. I am sorry I do not have the log data but here is a screenshot showing the issue of author not being passed into post meta, which you can replicate.

http://screencast.com/t/8sZOaOvHz

I ramble toward the end, trying to troubleshoot a bit. 

Hope this helps.

Andy Golay

**Comment by sc0ttkclark** [comment]
This should be fixed as part of the fix in #61
