### ISSUE TITLE
MP3 fields causing WordPress to crash

### ISSUE THREAD

**Issue by pstollery** [pods-framework/pods-gravity-forms#51]
I have a gravity form and pod with an MP3 field. If I map them, on submitting the form I receive a 500 error from WordPress.

The entry in GF is created and the MP3 gets uploaded - but the POD fails to get generated. Therefore I'm assuming it's this plugin causing the 500 error.

**Comment by Ramoonus** [comment]
you don`t have a serverside error log?

**Comment by pstollery** [comment]
Fatal error: Call to undefined function wp_read_audio_metadata() in /gluster_data/cpanel/kmea/public_html/cpanel/wp-admin/includes/image.php on line 138

When switching debug on. Looks like a bug in the wordpress core?

**Comment by sc0ttkclark** [comment]
This looks like it was caused by Pods when using pods_attachment_import, this has been fixed in the upcoming Pods 2.7 release.
