### ISSUE TITLE
Feature Request - option for gravity form submission to update existing pod entry

### ISSUE THREAD

**Issue by chris-nc** [pods-framework/pods-gravity-forms#52]
I am building a front end system for allowing registered users to build a complex profile that consists of multiple types of pods data stored in multiple pods tables.

I am using Gravity Forms to populate those pods entries but I would also like to use Gravity Forms to replace the pods entry edit forms as well so I can have a more streamlined user interface.

Is there a simple mod I could make to accomplish this?

Or are there any module functions I could extend in the site functions.php file to update a pods record instead of creating a new one when a valid pods record id is present?

Thanks.

**Comment by sc0ttkclark** [comment]
Moving focus to #53
