### ISSUE TITLE
I can't use the same field content into a pod field and the title

### ISSUE THREAD

**Issue by EdithNet** [pods-framework/pods-gravity-forms#56]
Hello:
I've created a form and mapped all the pods fields. In the form, I have a field called "name", and I want this content to be passed to my pods "name" field but to my pos tittle too, but if I map this, one of them remain empty. Hoy can I do it?

**Comment by David-Brown** [comment]
"Name" is a reserved term in WordPress. That might be causing the issue. Have you tried re-naming the field?

**Comment by EdithNet** [comment]
The name of the field is "Nombre"

Larga y próspera vida
Edith

**Comment by sc0ttkclark** [comment]
@EdithNet are you still having trouble with this?

**Comment by jimtrue** [comment]
@EdithNet We haven't heard anything further from you on this since you initially opened the ticket in October of 2016. I'm closing this ticket as inactive. If you're still having this issue, please just respond to the ticket and we'll re-open.
