### ISSUE TITLE
Conflict between Pods and Gravity Form (total price item)

### ISSUE THREAD

**Issue by stddd** [pods-framework/pods-gravity-forms#57]
Hello ! 

I have a problem with Pods and Gravity Form.

Easiest with an example : [http://www.ffyb.be/boutique-ffyb/]

When i add item in the form, i don't see the total price increase still at 0, after few test ( desactivate a lot of plugins ) seems to be PODS the problem, i try to desactivate some JS of PODS to prevent the error.

I tested:  WP_DEBUG -> nothing, JS problem console-> nothing

PS : Pods is use for the Carousel of partners 

Thanks in advance !

**Comment by lukecav** [comment]
@stddd 

So are you using pricing fields on that form or something else?

https://www.gravityhelp.com/documentation/article/product/
https://www.gravityhelp.com/documentation/article/option/

**Comment by jimtrue** [comment]
@stddd We haven't heard anything further from you on this since you initially opened the ticket in November of 2016 (nor did you reply to @lukecav questions). I'm closing this ticket as inactive. If you're still having this issue, please just respond to the ticket and we'll re-open.
