### ISSUE TITLE
Form entry ID not available to be saved in pod?

### ISSUE THREAD

**Issue by rpall** [pods-framework/pods-gravity-forms#58]
I configured a pods feed for a form and wanted to store the original gf form entry id in a pods field. I mapped the pod custom field "GF entry id" to form field "Entry ID". However it doesn't get saved. The field for the pod record is saved empty.

Pods field was marked as required, tried both plain text and plain number, though it didn't make a difference. Even though the pod field was marked required, the record still saved with an empty value for "GF entry id".

Pod type: custom post type.

If someone could verify that this is an issue, that'd be great.

**Comment by rpall** [comment]
Fwiw i used this workaround for the time being. 

`add_action( 'pods_gf_to_pods', 'ph_add_author_to_request', 10, 5);
function ph_add_author_to_request( $pod, $save_action, $data, $id, $podsgf ) {
  $pod_id = $id;
  $entry_id = $podsgf->entry_id;
  $user_id = gf_user_registration()->get_user_by_entry_id( $entry_id, true );

  if ( !empty( $user_id ) ) {
    $request = pods( 'request', $pod_id );
    $request->save( 'author', $user_id );
  }
}`

**Comment by rpall** [comment]
Backstory: i was trying to achieve getting the author relationship to be set correctly when using the GF User registration add-on. I thought i could achieve this by making the connection via the gf entry id field, but this also was not saved to the pod.

For the time being i managed to achieve the proper author relationship by hooking into the `pods_gf_to_pods` hook like this:

```php
add_action( 'pods_gf_to_pods', 'ph_add_author_to_request', 10, 5);
function ph_add_author_to_request( $pod, $save_action, $data, $id, $podsgf ) {
  $pod_id = $id;
  $entry_id = $podsgf->entry_id;
  $user_id = gf_user_registration()->get_user_by_entry_id( $entry_id, true );

  if ( !empty( $user_id ) ) {
    $request = pods( 'request', $pod_id );
    $request->save( 'author', $user_id );
  }
}
```

**Comment by sc0ttkclark** [comment]
Why not use this hook?

`$data = apply_filters( 'pods_gf_to_pods_data', $data, $form, $options );`

https://github.com/pods-framework/pods-gravity-forms/blob/master/includes/Pods_GF.php#L1530

**Comment by sc0ttkclark** [comment]
Going to close this as resolved, let me know if you have any trouble with that hook.
