### ISSUE TITLE
Saving pod feed from form, but 2/10 fields are empty.

### ISSUE THREAD

**Issue by Titan92** [pods-framework/pods-gravity-forms#60]
After some updates, a few fields "nombre" "apellido_1" (Name Last Name in Spanish) not feeding correctly, empty on custom_post_type.

In the form log everything is ok.

all other fields get their value.

**Comment by sc0ttkclark** [comment]
Just following up on this, is your pod feed set up to map the first name and last name fields individually to the nombre/apellido_1 fields in the Pods feed settings?

**Comment by jimtrue** [comment]
@Titan92 We haven't heard anything further from you on this since you initially opened the ticket in March. I'm closing this ticket as inactive. If you're still having this issue, please just respond to the ticket and we'll re-open.
