### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by maarten00** [pods-framework/pods-gravity-forms#63]
The plugin is on version 1.2 on Wordpress.org:
https://wordpress.org/plugins/pods-gravity-forms/

But the tags here are not up-to-date with the version on WP.org. As I'm installing the plugin using Composer I'm not getting the latest release.
Could you please add tags for the latest releases?

**Comment by sc0ttkclark** [comment]
I haven't maintained a list of tags for this plugin, I'll go ahead and add them.

**Comment by sc0ttkclark** [comment]
Added
