### ISSUE TITLE
Categories & Tags Aren't Mapping

### ISSUE THREAD

**Issue by chriswagoner** [pods-framework/pods-gravity-forms#68]
Your update for media uploads worked wonderfully, but it broke the category, tag, and custom field mapping. Yikes!

**Comment by jimtrue** [comment]
Can you be more specific, because that would sound like it broke ALL custom field mapping?

**Comment by chriswagoner** [comment]
It did break ALL custom field mapping. Doesn't work.

**Comment by jimtrue** [comment]
You can't map any fields in your forms to any pods fields EXCEPT upload files?

**Comment by chriswagoner** [comment]
Correct. Unless I'm really screwing it up... I reverted to a previous version and that worked for categories, tags, and CF - but not media. Went back to the latest master and the media works, but Cats, Tags, and CF don't work at all.

**Comment by jimtrue** [comment]
I don't have a GF test site setup at present, so give me some time to setup a local test site specific for Gravity Forms. Make sure you also cleared Cache in the Pods Settings, Clear Cache.

**Comment by chriswagoner** [comment]
I got really hopeful for a minute. Clearing the POD cache didn't work.

**Comment by jimtrue** [comment]
I'm not seeing the issue you're seeing. All of my custom fields mapped, but my Categories & Tags also didn't work (they don't even show up in the Pods Feed portion). How do you have yours configured? Are you adding the fields as Post Objects?

Can you screenshot your Pods Feed page?

**Comment by jimtrue** [comment]
Well, that was odd, left to add a Custom Taxonomy to see if it had the same issue and when I came back my Pods Feed Settings had the Category & Tag options. 

My Custom Taxonomy did send over the id, not the actual Taxonomy selected field, so need to validate that one again.

**Comment by chriswagoner** [comment]
Categories and Tags don't work - but I will try deleting and starting over with those. You can see a POD new taxonomy here. I have tried standard checkboxes, tags, custom... nothing seems to work. Everything is feeding into the form Correctly.
Note: previously, when I would map tags, I had to have the same amount of "dummy" items in the field as PODS was populating so else it would give me an error that I hadn't selected everything. (i.e., if I had one checkbox as a placeholder, and POD fed 15 items in, if I didn't select the first check box I'd get an error.)
![pod feed](https://cloud.githubusercontent.com/assets/27773546/26311484/10f1e404-3eca-11e7-8347-81ceb52250da.png)

**Comment by jimtrue** [comment]
![screenshot 2017-05-22 09 38 05](https://cloud.githubusercontent.com/assets/3052875/26311497/7cab18ca-3ed2-11e7-8f7f-77218d78ac11.png)
This is what mine did; it actually added a new Uncategorized

My Tags mapped properly

![screenshot 2017-05-22 09 38 33](https://cloud.githubusercontent.com/assets/3052875/26311536/a4df24e4-3ed2-11e7-8e66-b4a8d735202a.png)
But my Custom Taxonomy added another Taxonomy that wasn't in the selection, although I selected SciFi for that one.

All of my select fields are Populate from Pods Feed. I don't add anything in their select lists.

How is that particular field `resource_type` configured at the Gravity Form level @chriswagoner ?

**Comment by chriswagoner** [comment]
The resource_type is configured as checkboxes and POD Feed is checked. On the form, it shows up with all the options. But nothing is fed through. SO, I changed the box type to tags - same. Changed it to custom - same.... I am deleting and retrying since it's working for you.

**Comment by jimtrue** [comment]
I'm mapping post tags to associated taxonomy 'tags'. There is no other 'field form' that acts like that, so I'm not sure it would work, but it should on a non-hierarchal taxonomy.

**Comment by chriswagoner** [comment]
Will try that now...

**Comment by sc0ttkclark** [comment]
Any luck?

**Comment by chriswagoner** [comment]
Everything seems to be working except multi-upload. Am I missing a POD setting or Gform? I tried a few options. If it's working for you, could you snapshot your settings?

**Comment by sc0ttkclark** [comment]
Just pushed some more fixes, please try again and let me know if I've covered all of the cases now. I've just tested post categories and tags too.

**Comment by jimtrue** [comment]
Everything worked for me (Categories, Tags, Multiple images). The only thing I still had an issue with was the Custom Taxonomy writing itself as the Term_ID, not mapping to the actual Taxonomy selected in the drop-down. I used Multiple-Select form input, but Mapped the only place it was available, in WP Objects.

**Comment by jimtrue** [comment]
![screenshot 2017-06-01 10 15 24](https://cloud.githubusercontent.com/assets/3052875/26683894/5af75a20-46b3-11e7-8d6f-a76ca5ec6fd2.png)

Here's what I'm seeing on multi-selection. It's basically writing the array as the value of the taxonomy.

**Comment by chriswagoner** [comment]
As far as I am concerned, the plug-in is fixed per the issue I started with. @jimtrue I think you still have an issue there, which happens to be with the multi-select. But it looks like you and @sc0ttkclark are on track. That may be the last bug left to squash. Checkbox multi-selection works for me.

Great work by both of you guys! Thanks for your help!

**Comment by sc0ttkclark** [comment]
@jimtrue Ready for another test.

Also you'll notice I just added the ability to prepopulate form fields based on the current post / current user (depending on the pod, but it follow similar logic to allowing editing)

**Comment by jimtrue** [comment]
Still doing the ["3","2"] on Genre

**Comment by jimtrue** [comment]
Oh duh, I need to pull code down, stand by

**Comment by jimtrue** [comment]
Fixed! You'll have to show me how to do the populate form fields based on current post/current user, so we can demonstrate that to others.

**Comment by chriswagoner** [comment]
@jimtrue when you create a dozen genres in the POD and only 3 items (default) in your form, can you get all of them to select and come through selected?

**Comment by sc0ttkclark** [comment]
If you have any other issues, please open a new ticket. Thanks!
