### ISSUE TITLE
Pod ID is not populating in the Form Entries List

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#73]
From this Forum Post: https://wordpress.org/support/topic/entry_id-is-not-sent-to-pod/

Verified on my local installation:
![screenshot 2017-06-27 11 22 30](https://user-images.githubusercontent.com/3052875/27595679-5c7b02c0-5b2b-11e7-88e7-6fcf6e2dc27e.png)

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
