### ISSUE TITLE
Bug: Post Image Field (in Post Fields) doesn't work for Featured Image

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#75]
Regular File Upload/image field works, but post image field does not.

**Comment by sc0ttkclark** [comment]
Please try the latest 1.4 I'm working on: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by jimtrue** [comment]
This still does not work. Verified against 1.4. The Post Image Form Field doesn't work but a regular image field mapped to Featured Image works fine.

**Comment by sc0ttkclark** [comment]
Fixed in 1.4
