### ISSUE TITLE
Bug: Autocomplete mapping hits Size Limit when Populating from Pods

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#79]
From this WordPress.org Forum Post:
https://wordpress.org/support/topic/populating-dropdown-with-pod-items-size-limit/

Validated that regular Relationship fields (drop-down select, etc.) are not running into this issue, only the AutoComplete field mappings

> The limit is not shown during the creation of the form but when the form is put onto a page. I actually tested it with different scenarios and found out that the limit only applies when I map a GF dropdown field to a POD auto complete field. By mapping a GF dropdown field to a POD dropdown field the problem is gone.

**Comment by sc0ttkclark** [comment]
Fixed in #86
