### ISSUE TITLE
Warning: strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by dlfdlf56** [pods-framework/pods-gravity-forms#80]
I'm trying to connect a custom post type from Pods to Gravity Forms and getting an error "Warning: strlen() expects parameter 1 to be string, array given in /public_html/wp-content/plugins/pods/classes/fields/text.php on line 202" whenever I submit a form. 

I'm running the following versions:
Wordpress 4.8
Gravity Forms 2.2.2
Pods 2.6.10
Pods Gravity Forms Add-on 1.3

**Comment by sc0ttkclark** [comment]
Please try the latest 1.4 I'm working on: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by dlfdlf56** [comment]
This appears to be fixed in the Beta version!  Thank you!

**Comment by sc0ttkclark** [comment]
Awesome!
