### ISSUE TITLE
parameter mismatch

### ISSUE THREAD

**Issue by kimsingleton** [pods-framework/pods-gravity-forms#83]
Immediately after submission of a gravity form that is writing to a pod, I get these warnings momentarily:

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 239

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 241

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 243

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 245

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 239

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 241

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 243

Warning: strtolower() expects parameter 1 to be string, array given in /home/mysite.com/atll/wp-content/plugins/pods/classes/fields/boolean.php on line 245

**Comment by sc0ttkclark** [comment]
Please try the latest 1.4 I'm working on: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip

**Comment by sc0ttkclark** [comment]
This was fixed in the latest 1.4 release: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip
