### ISSUE TITLE
Pods linked fields in a Gravity Form won't add any more

### ISSUE THREAD

**Issue by Brian-Milnes** [pods-framework/pods-gravity-forms#88]
I've been working on Gravity Forms with Pods Gravity Forms Add-On
Great, populating from Pods using Pull-downs to select.
Except it's stopped working for new Gravity Forms
Thought it was something I was doing wrong, but no, if I Duplicate a working form, it doesn't work - no pull down selections available.

**Comment by sc0ttkclark** [comment]
Did you mean to close this? Is there still a problem here?

**Comment by Brian-Milnes** [comment]
Thanks Scott, yes I meant to close it. (Or delete it, preferably)
The primary cause was that Duplicating a Gravity Form does not retain the Pods settings.
Thanks
Brian

**Comment by sc0ttkclark** [comment]
Sorry about that, I realllllly wish GF would duplicate Pods feeds, as well as when exporting/importing.

**Comment by sc0ttkclark** [comment]
I went ahead and reported to our contact at GF (feeds not included when duplicating or using export/import)

**Comment by Brian-Milnes** [comment]
OK, cool

**Comment by sc0ttkclark** [comment]
GF let me know I can add support for duplicating feeds:

https://github.com/pods-framework/pods-gravity-forms/commit/4fc3f86e07dfa186e4c93d7a8e9b75f397ee280b

That's now supported! Import/export is something they're still looking into but that's not part of your original problem. Happy coding!
