### ISSUE TITLE
Prefill data in form

### ISSUE THREAD

**Issue by mastef** [pods-framework/pods-gravity-forms#9]
This is great, and works right now for Gravity Forms > New Pods entry.

How would we approach now an 'edit' feature, where the gravity forms form is prefilled with the pods data? There is a feature in GF to allow for URL parameters to be used for prepopulation, see http://www.gravityhelp.com/documentation/page/Allow_field_to_be_populated_dynamically

I would think a hook will do it

**Comment by sc0ttkclark** [comment]
I'm not sure yet how best to handle this, but open to ideas. We have pre-filling already supported in Pods_GF so it's just a matter of somehow exposing an option of where to get the ID for the item to auto-populate from.

**Comment by sc0ttkclark** [comment]
Moving into #53
