### ISSUE TITLE
Enable populating field values for this form - tries to create a new CPT Entry

### ISSUE THREAD

**Issue by quasel** [pods-framework/pods-gravity-forms#92]
@sc0ttkclark in slack:
> Populating form fields with value of current post - Not saving but populating the form fields themselves for submit

if I'm not mistaken this option is only meant to prepopulate values based on Current $post_id but not save the form to the same CPT? It works but throws an error `Content, title, and excerpt are empty.` as it tries to creat a new entry afterwards ;) either add an option to not save to pods after submit or add another option 

in the end there are 3 use cases for a single feed which maybe should be exclusive ...
- Edit (prepopulate + save to same Pod Entry)
- Prepopulate + Save (new Pod Entry) = Duplication
- Prepopulate and don't save to the same pod (if needed add second feed to save not only to GF)

Use Case e.g 
An event CPT with a price and a Form to make a booking that get's the Price from the current Event

**Comment by sc0ttkclark** [comment]
If you don't have the content, title or excerpt populated in the feed mapping, it throws the error. One or more of those fields has to have a value when saving, I believe even when updating.

I was able to get create / update working with the latest 1.4 release. Please try the latest Pods GF 1.4 beta https://github.com/pods-framework/pods-gravity-forms/archive/1.4-beta.zip

**Comment by sc0ttkclark** [comment]
Resolved in 1.4
