### ISSUE TITLE
Yes/No Radio buttons not keeping their setting when form submitted

### ISSUE THREAD

**Issue by Hornet25** [pods-framework/pods-gravity-forms#94]
Dear Sirs,
I have set up a gravity form to update a Pod from the front end. All of the fields are working correctly apart from the Yes/No fields which do not appear to be storing the current status when the form is saved. The Pod has the field set up as a Yes/No with the input type being a Radio Button. The Gravity Form has fields as Radio Buttons and the Form Fields are correctly mapped to the Pods fields. I need these fields to be Yes/No because I have set up my template so that other text changes colour from Red to Green if the Yes/No field changes fro No to Yes.
Hope this all makes sense.
I look forward to hearing from you.
Kind regards,
Ian

**Comment by jimtrue** [comment]
@Hornet25 To help us out, if you can, please provide an export of the form in question using Gravity Form Export and also provide us the Pods Admin, Components: Migrate Packages export including your pods configuration and templates.

Thanks!

**Comment by Hornet25** [comment]
Scott,
I appreciate the workload, but I was wondering if there was any ideas as to the time frame for a response or fix.

Kind regards,

Ian

**Comment by jimtrue** [comment]
@sc0ttkclark Reference with JSON for Form & Migrate: Packages:
https://secure.helpscout.net/conversation/498781346/199?folderId=1630325

Internal HelpScout for Privacy reasons

**Comment by Hornet25** [comment]
Scott,

Is there any time frame on the issue I have raised? I just have a meeting with my client tomorrow and if possible would like to give some sort of timing update.

Kind regards,

Ian

**Comment by sc0ttkclark** [comment]
Please try the latest Pods GF 1.4 beta https://github.com/pods-framework/pods-gravity-forms/archive/1.4-beta.zip

This has now been resolved.
