### ISSUE TITLE
Pods Gravity Forms requires that the Pods and Gravity Forms core plugins be installed and activated.

### ISSUE THREAD

**Issue by Anil-official** [pods-framework/pods-gravity-forms#96]
when i install gravity forms Pods Showing this Notice
:**Gravity Forms requires that the Pods and Gravity Forms core plugins be installed and activated.**
kindly solve this issue as soon as possible

**Comment by jimtrue** [comment]
Do you have Pods and Gravity Forms installed and activated in your installation? They are both required to use this plugin.

**Comment by jimtrue** [comment]
@Anil-official Did you see my note above? Do you actually have Pods and Gravity Forms Installed and Activated? If you do not, you will continue to get the message above as the plugin requires **both** to be installed and activated.

**Comment by jimtrue** [comment]
I'm closing this one as we've not heard back from you @Anil-official The notice above is shown when you try to enable Pods Gravity Forms Add-on and either Pods or Gravity Forms are not installed and activated.
