### ISSUE TITLE
Possible Caching bug - IIS 7.5

### ISSUE THREAD

**Issue by mgratch** [pods-framework/pods-gravity-forms#97]
I have a weird GF + Pods + ?Caching? issue.  Maybe any light can be shed....

Always the first drop down field will lose its GF to Pods connection (no matter which drop down, I have rearranged them, I have deleted them and created new ones etc)  I then clear pods cache and it works for 1 page reload. Then it stops.  The site is running on iis 7.5 with no caching at all and php 5.6, see details here https://d.pr/free/i/I95uQi

See a demo here

https://d.pr/free/v/wtuScN

I am limited on debugging as it seems to be working locally but I am running vvv and I have no server access... and to boot I am doing a favor :slightly_smiling_face: SO of course it's complicated.

**Comment by sc0ttkclark** [comment]
Not sure myself what would cause this initially. Have you tried using Pods Alternative Cache to see if it alleviates any issues here?

**Comment by mgratch** [comment]
Nothing IIS related -- I was able to recreate it on VVV. I will submit a patch soon.

**Comment by mgratch** [comment]
it seems `self::$related_objects` is not setup yet when the first field replacement is fired.

https://github.com/pods-framework/pods/blob/2.x/classes/fields/pick.php#L1977

**Comment by mgratch** [comment]
adding `$this->setup_related_objects( true )` to the conditional statement https://github.com/pods-framework/pods/blob/2.x/classes/fields/pick.php#L1977 fixes it, I don't have the time to work out why.... please let me know if you can shed some light on this. Otherwise I will circle back if I have time later.

**Comment by sc0ttkclark** [comment]
@jimtrue can you bring this over to the Pods repo so Phil can look? Appears to be a Pods bug, not Pods GF
