### ISSUE TITLE
Multi-Select Issue - Front End Editing

### ISSUE THREAD

**Issue by tehkz77** [pods-framework/pods-gravity-forms#98]
When using "Populate Related Items", it works great if it's a single select item.  However, if it is a multi-select (check-box, auto complete, etc..) no data is displayed and I get the following.
With WP Debug = True I get pages and pages of:
Warning: explode() expects parameter 2 to be string, array given in /home/******/public_html/wp-content/plugins/gravityforms/forms_model.php on line 3348
Warning: explode() expects parameter 2 to be string, array given in /home/*******/public_html/wp-content/plugins/gravityforms/forms_model.php on line 3349
Warning: in_array() expects parameter 2 to be array, null given in /home/*******/public_html/wp-content/plugins/gravityforms/forms_model.php on line 3351
Warning: in_array() expects parameter 2 to be array, null given in /home/*******/public_html/wp-content/plugins/gravityforms/forms_model.php on line 3351

In our current scenario there are currently about 22,000 entries.

[pods_config.json.txt](https://github.com/pods-framework/pods-gravity-forms/files/1752799/pods_config.json.txt)
[gravityforms-export-2018-02-23.json.txt](https://github.com/pods-framework/pods-gravity-forms/files/1752817/gravityforms-export-2018-02-23.json.txt)

**Comment by tehkz77** [comment]
Afternoon,  just wondering if this has been looked at and if there is anymore information I can provide.
thx

**Comment by sc0ttkclark** [comment]
Please try the latest Pods GF 1.4 beta https://github.com/pods-framework/pods-gravity-forms/archive/1.4-beta.zip
