### ISSUE TITLE
Pods feed supplying Last name not full name from GF name block. 

### ISSUE THREAD

**Issue by ghost** [pods-framework/pods-gravity-forms#99]
I’m using pods(2.7.1) and Gravity Forms(2.3.0) and Pods Gravity Forms Add-On(1.3). I have a Pod with a name field and a form that uses the Gravity form Name block. I have created a Pods feed to save the FULL name from the gravity form to the Pod. However ONLY the last name is saved.

**Comment by sc0ttkclark** [comment]
Please try the latest Pods GF 1.4 beta https://github.com/pods-framework/pods-gravity-forms/archive/1.4-beta.zip
